dist: xenial
addons:
  chrome: stable
language: node_js
services:
- xvfb
node_js:
- "12"
cache: yarn
before_install:
- export START_TIME=$( date +%s )
- export COVERALLS_SERVICE_JOB_ID=$( TRAVIS_JOB_ID )
- export COVERALLS_SERVICE_NAME="CKEditor5 code coverage"
- npm i -g yarn
install:
- yarn install
script:
- ./scripts/ci/travis-check.js
# "travis_wait" does not work in child processes. Hence, it must be called from the configuration file.
- if [[ $TRAVIS_JOB_TYPE == "Validation" && $TRAVIS_TEST_RESULT -eq 0 ]]; then travis_wait 30 yarn run docs:build-and-publish-nightly; fi
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  jobs:
  - TRAVIS_JOB_TYPE=Tests
  - TRAVIS_JOB_TYPE=Validation
